[tool]
id = "com.thelightphone.toolmanagerdemo"
label = "Tool Manager Demo"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.INTERNET"]
capabilities = ["tool-manager-provider"]
# change if you run this on the emulator!
 serverPackage = "com.thelightphone.sdk.emulator"
#serverPackage = "com.lightos"
