package com.thelightphone.plugin

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration

class LightSdkProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var processed = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed) return emptyList()
        processed = true

        val initialScreens = resolver
            .getSymbolsWithAnnotation("com.thelightphone.sdk.InitialScreen")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        val entryPoints = resolver
            .getSymbolsWithAnnotation("com.thelightphone.sdk.EntryPoint")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        val jobs = resolver
            .getSymbolsWithAnnotation("com.thelightphone.sdk.LightJob")
            .filterIsInstance<KSPropertyDeclaration>()
            .toList()

        // Validate @InitialScreen
        if (initialScreens.size > 1) {
            logger.error(
                "@InitialScreen must be applied to exactly one class. Found: " +
                initialScreens.joinToString { it.qualifiedName?.asString() ?: "unknown" }
            )
            return emptyList()
        }

        // Validate @EntryPoint
        if (entryPoints.size > 1) {
            logger.error(
                "@EntryPoint must be applied to exactly one object. Found: " +
                entryPoints.joinToString { it.qualifiedName?.asString() ?: "unknown" }
            )
            return emptyList()
        }

        entryPoints.firstOrNull()?.let { ep ->
            if (ep.classKind != ClassKind.OBJECT) {
                logger.error("@EntryPoint must be applied to an object, not a class: ${ep.qualifiedName?.asString()}")
                return emptyList()
            }
        }

        val jobEntries = collectJobEntries(jobs, "LightJob", "com.thelightphone.sdk.LightJob")
            ?: return emptyList()

        val initialScreenFqcn = initialScreens.firstOrNull()?.qualifiedName?.asString()
        val entryPointFqcn = entryPoints.firstOrNull()?.qualifiedName?.asString()

        // Collect all source files that contributed
        val allFiles = (initialScreens + entryPoints + jobs).mapNotNull { it.containingFile }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *allFiles.toTypedArray()),
            packageName = "com.thelightphone.sdk.generated",
            fileName = "LightSdkRegistry"
        )

        file.bufferedWriter().use { writer ->
            writer.write(buildString {
                appendLine("package com.thelightphone.sdk.generated")
                appendLine()
                appendLine("// Generated by LightSdkProcessor — do not edit")
                appendLine("object LightSdkRegistry {")
                if (initialScreenFqcn != null) {
                    appendLine("    val initialScreenFactory: (com.thelightphone.sdk.SealedLightActivity) -> com.thelightphone.sdk.SimpleLightScreen<*> = { $initialScreenFqcn(it) }")
                } else {
                    appendLine("    val initialScreenFactory: ((com.thelightphone.sdk.SealedLightActivity) -> com.thelightphone.sdk.SimpleLightScreen<*>)? = null")
                }
                if (entryPointFqcn != null) {
                    appendLine("    val entryPoint: com.thelightphone.sdk.LightEntryPoint = $entryPointFqcn")
                } else {
                    appendLine("    val entryPoint: com.thelightphone.sdk.LightEntryPoint? = null")
                }
                appendJobMap("jobs", "com.thelightphone.sdk.LightJobHandler", jobEntries)
                appendLine("}")
            })
        }

        return emptyList()
    }

    /** The `key` argument of a `@LightJob` annotation on [declaration], or null if missing. */
    private fun extractAnnotationKey(
        declaration: KSAnnotated,
        annotationShortName: String,
        annotationFqn: String,
    ): String? {
        val annotation = declaration.annotations.first {
            it.shortName.asString() == annotationShortName &&
                it.annotationType.resolve().declaration.qualifiedName?.asString() == annotationFqn
        }
        return annotation.arguments
            .firstOrNull { it.name?.asString() == "key" }?.value as? String
            ?: (annotation.arguments.firstOrNull()?.value as? String)
    }

    /** Validates a `@LightJob`-annotated property list into (key, handler fqn) pairs. */
    private fun collectJobEntries(
        properties: List<KSPropertyDeclaration>,
        annotationShortName: String,
        annotationFqn: String,
    ): List<Pair<String, String>>? {
        val entries = mutableListOf<Pair<String, String>>()
        val seenKeys = mutableSetOf<String>()
        for (job in properties) {
            val fqn = job.qualifiedName?.asString() ?: "unknown"
            if (job.parentDeclaration != null) {
                logger.error("@$annotationShortName must be applied to a top-level property: $fqn")
                return null
            }

            val typeFqn = job.type.resolve().declaration.qualifiedName?.asString()
            if (typeFqn != "com.thelightphone.sdk.LightJobHandler") {
                logger.error("@$annotationShortName property $fqn must be of type LightJobHandler (got $typeFqn)")
                return null
            }

            val key = extractAnnotationKey(job, annotationShortName, annotationFqn)
            if (key.isNullOrEmpty()) {
                logger.error("@$annotationShortName $fqn is missing a key")
                return null
            }
            if (!seenKeys.add(key)) {
                logger.error("Duplicate @$annotationShortName key '$key' on $fqn")
                return null
            }

            entries += key to fqn
        }
        return entries
    }

    /** Emits `val <name>: Map<String, <valueType>> = mapOf(...)` into a [StringBuilder]. */
    private fun StringBuilder.appendJobMap(name: String, valueType: String, entries: List<Pair<String, String>>) {
        appendLine("    val $name: Map<String, $valueType> = mapOf(")
        for ((key, fqn) in entries) {
            appendLine("        \"${key.replace("\"", "\\\"")}\" to $fqn,")
        }
        appendLine("    )")
    }
}

class LightSdkProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return LightSdkProcessor(environment.codeGenerator, environment.logger)
    }
}
