[tool]
id = "com.thelightphone.flights"
label = "Flights"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.INTERNET"]
capabilities = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
