[tool]
id = "com.thelightphone.uidemo"
label = "Light UI Demo"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.CAMERA", "android.permission.ACCESS_FINE_LOCATION"]
#serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"